beds/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('patient_reg/', views.patient_reg, name='patient_reg'),
]

covidportal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    url(r'^accounts/', include('django.contrib.auth.urls')),
    path('beds/', include('beds.urls')),
    path('admin/', admin.site.urls),
]

'''
accounts/login/ is used to log a user into your application. Refer to it by the name "login".

accounts/logout/ is used to log a user out of your application. Refer to it by the name "logout".

accounts/password_change/ is used to change a password. Refer to it by the name "password_change".

accounts/password_change/done/ is used to show a confirmation that a password was changed. Refer to it by the name "password_change_done".

accounts/password_reset/ is used to request an email with a password reset link. Refer to it by the name "password_reset".

accounts/password_reset/done/ is used to show a confirmation that a password reset email was sent. Refer to it by the name "password_reset_done".

accounts/reset/<uidb64>/<token>/ is used to set a new password using a password reset link. Refer to it by the name "password_reset_confirm".

accounts/reset/done/ is used to show a confirmation that a password was reset. Refer to it by the name "password_reset_complete".



'''

beds/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# after adding all models here, execute the below commands
# python manage.py makemigrations
# python manage.py migrate
dt = (
('AL', 'Alappuzha'),
('ER', 'Ernakulam'),
('ID', 'Idukki'),
('KN', 'Kannur'),
('KS', 'Kasargod'),
('KL', 'Kollam'),
('KT', 'Kottayam'),
('KZ', 'Kozhikode'),
('MA', 'Malappuram'),
('PL', 'Palakkad'),
('PT', 'Pathanamthitta'),
('TV', 'Thiruvananthapuram'),
('TS', 'Thrissur'),
('WA', 'Wayanad')
)
class Hospital(models.Model):
    sc = (
    ('gov', 'Government'),
    ('prv', 'Private')
    )
    name = models.CharField(max_length=50)
    location = models.CharField(max_length=50)
    district = models.CharField(max_length=2, choices=dt)
    phone = models.CharField(max_length=12)
    sector = models.CharField(max_length=3, choices=sc)
    covid_beds = models.IntegerField()
    normal_beds = models.IntegerField()
    icu_beds = models.IntegerField()
    ventilator = models.IntegerField()
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name+" "+self.location

class Patient(models.Model):
    ct = (
    ('cv', 'Covid'),
    ('nc', 'Non-Covid')
    )
    st = (
    ('W', 'Waiting'),
    ('A', 'Admitted'),
    ('D', 'Discharged')
    )
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    aadharno = models.IntegerField()
    phone = models.CharField(max_length=12)
    location = models.CharField(max_length=50)
    district = models.CharField(max_length=2, choices=dt)
    category = models.CharField(max_length=2, choices=ct)
    status = models.CharField(max_length=2, choices=st, blank=True, default='W')

    def __str__(self):
        return self.name

class BedAllocation(models.Model):
    ct = (
    ('C','Covid'),
    ('N','Normal'),
    ('I', 'ICU'),
    ('V', 'Ventilator')
    )
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE)
    category =  models.CharField(max_length=2, choices=ct)

    def __str__(self):
        return self.patient.name +" admitted on "+self.hospital.name

beds/forms.py
from django.forms import ModelForm
from.models import Patient

class PatientForm(ModelForm):
    class Meta:
        model = Patient
        fields = ['name', 'age', 'location', 'district', 'phone', 'aadharno', 'category']

beds/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Hospital, Patient, BedAllocation
from django.db.models import Sum
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import PatientForm
from django.shortcuts import redirect
# Create your views here.

def index(request):
    normal_beds = Hospital.objects.aggregate(total=Sum('normal_beds'))
    covid_beds = Hospital.objects.aggregate(total=Sum('covid_beds'))
    icu = Hospital.objects.aggregate(total=Sum('icu_beds'))
    ventilator = Hospital.objects.aggregate(total=Sum('ventilator'))

    page = request.GET.get('page', 1)
    hospital_list = Hospital.objects.all()
    paginator = Paginator(hospital_list, 5)
    try:
        hospitals = paginator.page(page)
    except PageNotAnInteger:
        hospitals = paginator.page(1)
    except EmptyPage:
        hospitals = paginator.page(paginator.num_pages)

    context = {
        'normal_beds': normal_beds,
        'covid_beds': covid_beds,
        'icu': icu,
        'ventilator': ventilator,
        'hospitals': hospitals
    }
    return render(request, 'beds/summary.html', context)

@login_required
def dashboard(request):
    
    return render(request, 'beds/dashboard.html')

def patient_reg(request):
    form = PatientForm(request.POST or None)
    context= {
    'form':form
    }
    if form.is_valid():
        form.save()
        return redirect('index')
    return render(request, 'beds/patient_registration.html', context)

beds/templates/beds/dashboard.html
{% extends 'beds/index.html' %}

{% block content %}
<h2> Welcome {{ user.username }} </h2>
{% endblock %}

beds/templates/beds/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <title>Covid Portal</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'beds/css/style.css'%}">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="navbar navbar-expand-sm bg-navy navbar-dark">
  <div class="container">
    <!-- Brand -->
    <a class="navbar-brand" href="#"><i class="fa fa-heartbeat fa-lg"></i> COVID PORTAL</a>

    {% if user.is_authenticated %}
    <!-- Links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'index' %}"><i class="fa fa-home"></i> Home </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard' %}"><i class="fa fa-dashboard"></i> Dashboard </a>
      </li>
      <!-- Dropdown -->
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
          <i class="fa fa-user-circle"></i> {{ user.username }}
        </a>
        <div class="dropdown-menu">
           <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
        </div>
      </li>
     </ul>
   {% else %}
    <!-- Links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}"><i class="fa fa-lock"></i> Hospital Login</a>
      </li>
      <li class="nav-item">
        <a class="btn btn-warning" href="{% url 'patient_reg' %}"><i class="fa fa-user-o"></i> Patient Registration</a>
      </li>
    </ul>
    {% endif %}

  </div>
</nav>
<div class="container">
  {% block content %}

  {% endblock %}
</div>

<footer class="footer" style="position:fixed; bottom:0; width:100%;">
  <div class="container-fluid p-4">
    <p class="text-center"> &copy; 2021. All Rights Reserved.</p>
  </div>
</footer>
</body>
</html>

beds/templates/beds/patient_registration.html
{% extends 'beds/index.html' %}

{% block content %}
<div class="container m-4 p-4">
  <h3> Patient Registration </h3>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-danger">
  </form>
</div>
{% endblock %}

beds/templates/beds/summary.html
{% extends 'beds/index.html' %}

{% block content %}
<div class="container mt-4 pt-4 pb-4">
  <div class="card-deck">
    <div class="card bg-primary">
      <div class="card-body text-center">
        <p class="card-text">NORMAL BEDS</p>
        <h2 class="text-white">{{ normal_beds.total }}</h2>
      </div>
    </div>
    <div class="card bg-warning">
      <div class="card-body text-center">
        <p class="card-text">COVID BEDS</p>
        <h2 class="text-white">{{ covid_beds.total }}</h2>
      </div>
    </div>
    <div class="card bg-success">
      <div class="card-body text-center">
        <p class="card-text">ICUs</p>
        <h2 class="text-white">{{ icu.total }}</h2>
      </div>
    </div>
    <div class="card bg-danger">
      <div class="card-body text-center">
        <p class="card-text">VENTILATOR</p>
        <h2 class="text-white">{{ ventilator.total }}</h2>
      </div>
    </div>
  </div>
</div>

<div class="container mt-3">
  <h3 class="mb-3">Hospital Information</h3>
  <input class="form-control" id="myInput" type="text" placeholder="Search..">
  <br>
  <table class="table table-bordered table-striped table-hover">
    <thead class="thead-dark">
      <tr>
        <th>NAME</th>
        <th>LOCATION</th>
        <th>DISTRICT</th>
        <th class="text-center">NORMAL BEDS</th>
        <th class="text-center">COVID BEDS</th>
        <th class="text-center">ICU</th>
        <th class="text-center">VENTILATOR</th>
      </tr>
    </thead>
    <tbody id="myTable">
      {% for hospital in hospitals %}
        <tr>
          <td>{{ hospital.name }}</td>
          <td>{{ hospital.location}}</td>
          <td>{{ hospital.get_district_display}}</td>
          <td class="text-center">{{ hospital.normal_beds}}</td>
          <td class="text-center">{{ hospital.covid_beds}}</td>
          <td class="text-center">{{ hospital.icu_beds}}</td>
          <td class="text-center">{{ hospital.ventilator}}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% if hospitals.has_other_pages %}
  <nav aria-label="Pagination">
    <ul class="pagination justify-content-center">
      {% if hospitals.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ hospitals.previous_page_number }}">Previous</a></li>
      {% else %}
        <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1">Previous</a></li>
      {% endif %}
      {% for i in hospitals.paginator.page_range %}
        {% if hospitals.number == i %}
          <li class="page-item active"><a class="page-link" href="#"><span>{{ i }} <span class="sr-only">(current)</span></span></a></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if hospitals.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ hospitals.next_page_number }}">Next</a></li>
      {% else %}
        <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}
  <div style="height:120px;"></div>
</div>
<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
{% endblock %}